"""initial migration

Revision ID: a8e24481caa0
Revises: 
Create Date: 2026-05-20 15:09:05.999702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e24481caa0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('difficulty', sa.Enum('Easy', 'Medium', 'Hard', name='difficulty_enum'), nullable=False),
    sa.Column('problem_type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_problems_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Solved', 'Attempted', 'Unsolved', name='status_enum'), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.Column('solution_notes', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_attempts_problem_id_problems')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempts')
    op.drop_table('problems')
    op.drop_table('users')
    # ### end Alembic commands ###
